name: hackernews
description: HackerNews reader

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.3
  json_annotation: ^4.6.0
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.1.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Corben
      fonts:
        - asset: assets/fonts/Corben-Bold.ttf

flutter_icons:
  image_path: assets\images\launch_image.png
  android: true
  ios: true
